# Site settings
title: "machete"
description: "Powerful tooling for json schema"
baseurl: "/validation/" # the subpath of your site, e.g. /blog/
url: "http://machete-php.github.io" # the base hostname & protocol for your site
author: "Matt Allan"

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
