# Site settings
title: "machete"
description: "Powerful tooling for json schema"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://machete-php.github.io" # the base hostname & protocol for your site
author: "Matt Allan"

# Build settings
markdown: redcarpet
redcarpet:
  extensions:
    - footnotes
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough